# docker-compose.yml
version: "3.8"

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    command: streamlit run Data_Analysis_App_Wireframe.py --server.port=8501 --server.address=0.0.0.0
