version: "3.8"

services:
  streamlit:
    # Instead of build: ., just use the Docker image from Docker Hub
    image: "${DOCKERHUB_USERNAME}/streamlit:latest"
    container_name: streamlit_app

    # Optionally ensure it always pulls the latest from Docker Hub
    # (requires docker-compose v2.4+ for pull_policy)
    # pull_policy: always

    ports:
      - "${STREAMLIT_PORT}:${STREAMLIT_PORT}"

    # If you still have dynamic environment variables in .env, use env_file:
    env_file:
      - .env

    # If you want local files mounted (for development) keep it;
    # otherwise remove this to rely on what's baked into the image
    # volumes:
    #   - .:/app

    depends_on:
      - mongo

    # Possibly change the command if the code is baked in the image
    command: streamlit run Overview.py \
             --server.port=${STREAMLIT_PORT} \
             --server.address=0.0.0.0

  mongo:
    image: "mongo:${MONGO_VERSION}"
    container_name: "${MONGO_CONTAINER_NAME}"
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
