name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ########################################################################
  # Job 1: Conditionally Build & Push Docker Image
  ########################################################################
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------------------------------------
      # (1) Check out the repository
      # -------------------------------------------------------------
      - name: Check out code
        uses: actions/checkout@v3

      # -------------------------------------------------------------
      # (2) Determine if Docker build is needed
      #     Compare github.event.before to github.sha
      # -------------------------------------------------------------
      - name: Check if Docker build is needed
        id: docker-check
        shell: bash
        run: |
          # Fetch all history and tags
          git fetch --prune --unshallow
          
          previous_commit=${{ github.event.before }}
          current_commit=${{ github.sha }}
          
          # If "before" is all zeroes, there's no previous commit (new branch/initial commit)
          if [[ "$previous_commit" == "0000000000000000000000000000000000000000" ]]; then
            echo "No previous commit found (new branch or initial commit). Forcing build."
            echo "build_needed=true" >> $GITHUB_OUTPUT
          else
            echo "Comparing changes from $previous_commit to $current_commit"
            
            # Use git diff to check for changes in specific files
            if git diff --name-only $previous_commit $current_commit | grep -q -E '^(Dockerfile|requirements\.txt)$'; then
              echo "Changes detected in Dockerfile or requirements.txt"
              echo "build_needed=true" >> $GITHUB_OUTPUT
            else
              echo "No changes detected in Dockerfile or requirements.txt"
              echo "build_needed=false" >> $GITHUB_OUTPUT
            fi
          fi

      # -------------------------------------------------------------
      # (3) Set up Docker Buildx (for caching + multi-platform if needed)
      # -------------------------------------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # -------------------------------------------------------------
      # (4) Log in to Docker Hub
      # -------------------------------------------------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -------------------------------------------------------------
      # (5) Build & push Docker image with caching (only if needed)
      # -------------------------------------------------------------
      - name: Build and Push Docker image
        if: steps.docker-check.outputs.build_needed == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/streamlit:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  ########################################################################
  # Job 2: Deploy Docker Container on Amazon Linux (EC2) via SSH
  ########################################################################
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  # Ensures this job runs AFTER build-and-push

    steps:
      # -------------------------------------------------------------
      # (1) SSH Setup
      # -------------------------------------------------------------
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # -------------------------------------------------------------
      # (2) SSH into EC2 and run deployment steps
      # -------------------------------------------------------------  
      - name: Deploy to Amazon Linux EC2
        run: |
          # Use keep-alive SSH options to prevent broken pipe
          ssh -o StrictHostKeyChecking=no \
              -o ServerAliveInterval=60 \
              -o ServerAliveCountMax=2 \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            
            # Exit on errors, show commands, treat unset vars as errors, fail on pipe errors
            set -euxo pipefail

            echo "Starting deployment on Amazon Linux EC2 with Docker Compose..."

            #################################################################
            # A. Install & start Docker + Docker Compose
            #################################################################
            echo "Updating system packages and installing Docker..."
            sudo yum update -y
            sudo yum install -y docker git curl

            echo "Enabling and starting Docker..."
            sudo systemctl enable docker
            sudo systemctl start docker

            # Check if Docker Compose is installed
            if ! command -v docker-compose &> /dev/null; then
              echo "Installing Docker Compose..."
              # Adjust the version if you want a newer or older version
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" \
                -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            else
              echo "Docker Compose is already installed."
            fi

            #################################################################
            # B. Clean up any existing CNN folder to avoid Git conflicts
            #################################################################
            if [ -d "CNN" ]; then
              echo "Removing old CNN directory..."
              rm -rf CNN
            fi

            #################################################################
            # C. Clone your repo fresh
            #################################################################
            echo "Cloning repository..."
            git clone https://github.com/TeachMeTW/CNN.git CNN
            cd CNN || { echo "Failed to enter CNN directory!"; exit 1; }

            #################################################################
            # D. Decode your Base64-encoded .env
            #################################################################
            # If your environment requires different flags for base64 decoding
            # (e.g. macOS might need `-D` instead of `-d`), adjust accordingly.
            echo "Decoding .env from DOTENV_FILE secret..."
            echo "${{ secrets.DOTENV_FILE }}" | base64 -d > .env

            # (Optional) For debugging, you can print the first few lines:
            # head .env

            #################################################################
            # E. Docker Compose: stop old containers, prune, build/run new
            #################################################################
            echo "Bringing down any existing containers..."
            sudo docker-compose down -v || true

            echo "Pruning unused Docker resources..."
            sudo docker system prune -af --volumes || true

            echo "Pulling & building images (no-cache) ..."
            sudo docker-compose pull || true
            sudo docker-compose build --no-cache

            echo "Starting containers in detached mode..."
            sudo docker-compose up -d

            #################################################################
            # F. Health Check
            #################################################################
            echo "Waiting for Streamlit to start..."
            sleep 10

            # Verify that the service is up on port 8501
            echo "Checking Streamlit health at http://localhost:8501..."
            if ! curl -f http://localhost:8501; then
              echo "Health check failed! Check logs or revert changes."
              # Optionally do a rollback or additional steps if needed
              exit 1
            fi

            echo "Health check passed! Deployment is successful."

            #################################################################
            # G. Final Docker Cleanup (Optional)
            #################################################################
            sudo docker system prune -af --volumes || true

            echo "Deployment completed successfully."
          EOF
  ########################################################################
  # Job 3: Configure Nginx as Reverse Proxy for cisconeural.net
  ########################################################################
  configure-nginx:
    runs-on: ubuntu-latest
    needs: deploy  # Runs AFTER the 'deploy' job completes

    steps:
      # -------------------------------------------------------------
      # (1) SSH Setup
      # -------------------------------------------------------------
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # -------------------------------------------------------------
      # (2) SSH into EC2 and configure Nginx + Docker container
      # -------------------------------------------------------------
      - name: Configure Nginx on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            set -x
            echo "Configuring Nginx on Amazon Linux EC2..."
            
            sudo mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak 2>/dev/null || true
            
            echo '${{ secrets.NGINX_CONFIG }}' | sudo tee /etc/nginx/conf.d/streamlit.conf
            
            sudo docker stop streamlit-container 2>/dev/null || true
            sudo docker rm streamlit-container 2>/dev/null || true
            sudo docker pull robinttw/streamlit:latest
            sudo docker run -d \
              --name streamlit-container \
              -p 8501:8501 \
              robinttw/streamlit:latest
            
            sudo docker ps
            
            sudo nginx -t
            sudo systemctl restart nginx
            echo "Done configuring Nginx and Streamlit container."
          EOF
