name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ########################################################################
  # Job 1: Conditionally Build & Push Docker Image
  ########################################################################
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------------------------------------
      # (1) Check out the repository
      # -------------------------------------------------------------
      - name: Check out code
        uses: actions/checkout@v3

      # -------------------------------------------------------------
      # (2) Determine if Docker build is needed
      #     Compare github.event.before to github.sha
      # -------------------------------------------------------------
      - name: Check if Docker build is needed
        id: docker-check
        shell: bash
        run: |
          # Fetch all history and tags
          git fetch --prune --unshallow
          
          previous_commit=${{ github.event.before }}
          current_commit=${{ github.sha }}
          
          # If "before" is all zeroes, there's no previous commit (new branch/initial commit)
          if [[ "$previous_commit" == "0000000000000000000000000000000000000000" ]]; then
            echo "No previous commit found (new branch or initial commit). Forcing build."
            echo "build_needed=true" >> $GITHUB_OUTPUT
          else
            echo "Comparing changes from $previous_commit to $current_commit"
            
            # Use git diff to check for changes in specific files
            if git diff --name-only $previous_commit $current_commit | grep -q -E '^(Dockerfile|requirements\.txt)$'; then
              echo "Changes detected in Dockerfile or requirements.txt"
              echo "build_needed=true" >> $GITHUB_OUTPUT
            else
              echo "No changes detected in Dockerfile or requirements.txt"
              echo "build_needed=false" >> $GITHUB_OUTPUT
            fi
          fi

      # -------------------------------------------------------------
      # (3) Set up Docker Buildx (for caching + multi-platform if needed)
      # -------------------------------------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # -------------------------------------------------------------
      # (4) Log in to Docker Hub
      # -------------------------------------------------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -------------------------------------------------------------
      # (5) Build & push Docker image with caching (only if needed)
      # -------------------------------------------------------------
      - name: Build and Push Docker image
        if: steps.docker-check.outputs.build_needed == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/streamlit:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  ########################################################################
  # Job 2: Deploy Docker Container on Amazon Linux (EC2) via SSH
  ########################################################################
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  # Ensures this job runs AFTER build-and-push

    steps:
      # -------------------------------------------------------------
      # (1) SSH Setup
      # -------------------------------------------------------------
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # -------------------------------------------------------------
      # (2) SSH into EC2 and run deployment steps
      # -------------------------------------------------------------
      - name: Deploy to Amazon Linux EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            set -x
  
            echo "Starting deployment on Amazon Linux EC2 with Docker Compose..."
  
            #################################################################
            # A. Install and start Docker + docker-compose (if needed)
            #################################################################
            # Update packages and install Docker (if not already installed)
            sudo yum update -y
            sudo yum install -y docker
  
            # Start Docker if not running
            sudo systemctl start docker
            sudo systemctl enable docker
  
            # Install docker-compose if it isn't already installed.
            # For Amazon Linux, you may need to install extra packages or
            # manually download docker-compose; adjust as needed:
            if ! command -v docker-compose &> /dev/null
            then
              echo "Installing docker-compose..."
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" \
                -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            else
              echo "docker-compose is already installed."
            fi
  
            #################################################################
            # B. Remove existing CNN directory (avoid Git errors)
            #################################################################
            if [ -d "CNN" ]; then
              echo "Removing existing CNN directory..."
              rm -rf CNN
            fi
  
            #################################################################
            # C. Clone your repo fresh
            #################################################################
            echo "Cloning the repository..."
            git clone https://github.com/TeachMeTW/CNN.git CNN
            cd CNN || { echo "Failed to enter CNN directory! Exiting."; exit 1; }
  
            #################################################################
            # D. Decode your Base64-encoded .env and place it in CNN dir
            #################################################################
            echo "Decoding .env from DOTENV_FILE secret..."
            # Make sure ${{ secrets.DOTENV_FILE }} is your Base64-encoded .env
            echo "${{ secrets.DOTENV_FILE }}" | base64 -d > .env
  
            echo "Contents of .env file (for debug, optional):"
            cat .env
  
            #################################################################
            # E. Build and run Docker Compose
            #################################################################
            echo "Bringing up Docker Compose services..."
            sudo docker-compose pull || true
            sudo docker-compose build --no-cache
            sudo docker-compose up -d
  
            echo "Services are starting up..."
  
            #################################################################
            # F. (Optional) Basic health check
            #################################################################
            # Adjust the health check for your environment & service
            echo "Waiting for Streamlit to start..."
            sleep 10
  
            # Attempt to curl the service on port 8501
            if ! curl -f http://localhost:8501; then
              echo "Health check failed! Investigate logs."
              # Possibly do a rollback or additional debug steps
              exit 1
            fi
  
            echo "Health check passed! Deployment looks good."
  
            #################################################################
            # G. Clean up old Docker artifacts
            #################################################################
            sudo docker system prune -af --volumes || true
            sudo docker image prune -f || true
  
            echo "Deployment completed successfully."
          EOF


  ########################################################################
  # Job 3: Configure Nginx as Reverse Proxy for cisconeural.net
  ########################################################################
  configure-nginx:
    runs-on: ubuntu-latest
    needs: deploy  # Runs AFTER the 'deploy' job completes

    steps:
      # -------------------------------------------------------------
      # (1) SSH Setup
      # -------------------------------------------------------------
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # -------------------------------------------------------------
      # (2) SSH into EC2 and configure Nginx + Docker container
      # -------------------------------------------------------------
      - name: Configure Nginx on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            set -x
            echo "Configuring Nginx on Amazon Linux EC2..."
            
            sudo mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak 2>/dev/null || true
            
            echo '${{ secrets.NGINX_CONFIG }}' | sudo tee /etc/nginx/conf.d/streamlit.conf
            
            sudo docker stop streamlit-container 2>/dev/null || true
            sudo docker rm streamlit-container 2>/dev/null || true
            sudo docker pull robinttw/streamlit:latest
            sudo docker run -d \
              --name streamlit-container \
              -p 8501:8501 \
              robinttw/streamlit:latest
            
            sudo docker ps
            
            sudo nginx -t
            sudo systemctl restart nginx
            echo "Done configuring Nginx and Streamlit container."
          EOF
